### ISSUE TITLE
no server response with exception

### ISSUE THREAD

**Issue by wushuzh** [DMTF/Redfish-Mockup-Server#77]
I launch the server and run some request against it.

But after a while, the server cannot response to my query any more.

In the console, I found the following error msg

I am not sure how to troubleshooting this issue and more importantly how to aviod this happening ?

```

('GET', '/redfish/v1/Systems/1/Processors/1')
   GET: Headers: Host: 172.29.128.210
Accept-Encoding: identity


('GET', '/redfish/v1/Systems/1/Processors/2')
   GET: Headers: Host: 172.29.128.210
Accept-Encoding: identity


  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 392, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 321, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socket3.py", line 515, in send
    return self._sock.send(data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
10.244.1.1 - - [16/Nov/2020 03:34:41] "GET /redfish/v1/Chassis HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('10.244.1.1', 34169)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "./redfishMockupServer.py", line 376, in do_GET
    self.end_headers()
  File "/usr/local/lib/python3.8/http/server.py", line 529, in end_headers
    self.flush_headers()
  File "/usr/local/lib/python3.8/http/server.py", line 533, in flush_headers
    self.wfile.write(b"".join(self._headers_buffer))
  File "/usr/local/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socket3.py", line 534, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 392, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 321, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socket3.py", line 515, in send
    return self._sock.send(data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by mraineri** [comment]
Was this in a Docker container? How long was the server running before that happened?

From the exception trace I'm worried we might be digging down into Python HTTP server module...

**Comment by wushuzh** [comment]
I deployed it in k8s. It's running for a week or so.
Now I've added a livenessProbe and relaunch the server.

Anything I should do in case it happens again ?

**Comment by mraineri** [comment]
Not at this time... I don't have a good sense for what to instrument in the tool to help debug this further.

@billdodd any thoughts on steps to take to debug this?

**Comment by billdodd** [comment]
I don't have anything concrete, I'm afraid. Here are some comments and questions:

1. The traceback from the ConnectionResetError suggests that the client closed the connection before the server tried to send the response headers. Or the connection was closed on the server due to some error condition.
2. Was the error shown above the first error output by the server or the last? If it wasn't the first error, it would be good to be sure to capture that next time.
3. While digging down in the traceback, I noticed that the socket handling is using [gevent](https://pypi.org/project/gevent/) / [greenlet](https://greenlet.readthedocs.io/en/latest/). (`File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 392, in _sendall`) Does the problem occur if you use don't use a gevent/greenlet environment?
4. You mention that the server was up for about a week. Were client requests being sent continuously during that time or only occasionally? Wondering if there might have been some type of resource exhaustion.

**Comment by wushuzh** [comment]
After I add livenessProbe for the pod, now the kubernetes can notice the service is dead and restart it for me automatically. But still it happends from time to time.

For example, I started my pods for different type of redfish mockup servers today.  Here is the kubernetes pod status from `kubectl get pod` (I remove the pod name)
```
READY   STATUS    RESTARTS   AGE
1/1     Running   11         22h
1/1     Running   10         22h
1/1     Running   13         22h
1/1     Running   9          22h
1/1     Running   9          22h
1/1     Running   9          22h
1/1     Running   9          22h
1/1     Running   11         22h
1/1     Running   9          22h
1/1     Running   9          22h
1/1     Running   9          22h
1/1     Running   6          22h
1/1     Running   14         22h
1/1     Running   13         22h
1/1     Running   9          22h
1/1     Running   9          22h
1/1     Running   9          22h
1/1     Running   9          22h
1/1     Running   17         22h
1/1     Running   8          22h
1/1     Running   7          22h
1/1     Running   6          22h
1/1     Running   8          22h
1/1     Running   10         22h
1/1     Running   8          22h
1/1     Running   12         22h
1/1     Running   9          22h
1/1     Running   8          22h
1/1     Running   10         22h
1/1     Running   3          22h
1/1     Running   9          22h
1/1     Running   10         22h
```

**Comment by wushuzh** [comment]
my cluster are running on centos 7

```
Linux server44 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

And the requests being sent continuously. 

I checked the pod logs by `kubectl logs --previous podname ...`

(I could get the whole logs but I think it's too long to paste here, If needed, I will try to post it anyway)
The only exception I see in this log is as following:

```
10.244.1.1 - - [13/Jan/2021 08:32:14] "GET /redfish HTTP/1.1" 200 -
10.244.1.1 - - [13/Jan/2021 08:32:18] "GET /redfish/v1/Systems HTTP/1.1" 200 -
10.244.1.1 - - [13/Jan/2021 08:32:18] "GET /redfish/v1/Chassis HTTP/1.1" 200 -
10.244.1.1 - - [13/Jan/2021 08:32:18] "GET /redfish/v1/Chassis/1/NetworkAdapters HTTP/1.1" 404 -
10.244.1.1 - - [13/Jan/2021 08:32:18] "GET /redfish/v1/Systems/1 HTTP/1.1" 200 -
10.244.1.1 - - [13/Jan/2021 08:32:18] "GET /redfish/v1/Systems/1 HTTP/1.1" 200 -
10.244.1.1 - - [13/Jan/2021 08:32:48] "PATCH /redfish/v1/Systems/1 HTTP/1.1" 400 -
10.244.1.1 - - [13/Jan/2021 08:32:48] "GET /redfish HTTP/1.1" 200 -
('GET', '/redfish')
----------------------------------------
Exception happened during processing of request from ('10.244.1.1', 43154)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "./redfishMockupServer.py", line 415, in do_GET
    self.wfile.write(encoded_data)
  File "/usr/local/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 699, in sendall
    return _sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 409, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 338, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
10.244.1.1 - - [13/Jan/2021 08:32:48] "GET /redfish HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('10.244.1.1', 43180)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
   GET: Headers: Host: 10.244.1.42:80
User-Agent: kube-probe/1.18
Accept-Encoding: gzip
Connection: close

```
There are serveral log records as following the above exception:

```

('GET', '/redfish/v1/Systems/1/Storage')
   GET: Headers: Host: 172.29.128.240
Accept-Encoding: identity
Content-Type: application/json


('GET', '/redfish/v1/Systems/1/Storage/HA-RAID')
   GET: Headers: Host: 172.29.128.240
Accept-Encoding: identity
Content-Type: application/json


('GET', '/redfish/v1/Chassis/1/Power')
   GET: Headers: Host: 172.29.128.240
Accept-Encoding: identity
Content-Type: application/json


('GET', '/redfish/v1/Systems/1/Memory')
   GET: Headers: Host: 172.29.128.240
Accept-Encoding: identity
Content-Type: application/json


('GET', '/redfish/v1/Systems/1/Memory/1')
   GET: Headers: Host: 172.29.128.240
Accept-Encoding: identity
Content-Type: application/json

```

**Comment by billdodd** [comment]
This recent error is not identical to the original one reported, but it is very similar. In both cases, the mockup server is in do_GET() trying to send the response to the client. And the client connection was either reset by the client (ConnectionResetError, from the original error, reported Nov 16) or closed/shutdown (BrokenPipeError, from the new error, reported Jan 13).

And in both cases, the error is happening down in the third-party [gevent](https://pypi.org/project/gevent/) coroutine-based Python networking library. This library is not used directly by the mockup server and seems to have been enabled in your environment by monkey patching:

http://www.gevent.org/intro.html#monkey-patching

A couple of things you may want to investigate:

1. Since both of the errors seem to suggest that the client has closed the connection, investigate if and when the client is closing the connection abnormally (due to timeout or other reasons).
2. Leverage the monitoring capabilities gevent provides: http://www.gevent.org/monitoring.html

**Comment by wushuzh** [comment]
Thanks a lot for the suggestion, I will check the reference you mentioned.

**Comment by mraineri** [comment]
Have you made any progress on @billdodd's recommendations?

**Comment by mraineri** [comment]
No updated in a while. Closing; please reopen if the issue persists and further help is needed.
